# Generated by Django 3.2.4 on 2022-04-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_condominio_gastocomune_residente'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='telefono',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
    ]
