# Generated by Django 3.2.4 on 2022-04-29 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_residente_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='horario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='descripcion',
            field=models.TextField(default=0, max_length=200, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condominio',
            name='nro_vivienda',
            field=models.IntegerField(verbose_name='Nro de Viviendas'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creación Registro'),
        ),
    ]
