# Generated by Django 3.2.4 on 2022-04-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220428_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='espacio',
            name='descripcion',
            field=models.TextField(default=0, max_length=150, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='horario',
            field=models.CharField(default=0, max_length=20, verbose_name='Horario'),
            preserve_default=False,
        ),
    ]
