# Generated by Django 3.2.4 on 2022-04-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220428_2257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GastoComune',
            new_name='GastosComune',
        ),
        migrations.AlterField(
            model_name='espacio',
            name='descripcion',
            field=models.TextField(max_length=200, verbose_name='Descripción'),
        ),
    ]
