# Generated by Django 3.2.4 on 2022-04-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220428_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residente',
            name='depto',
        ),
        migrations.AddField(
            model_name='residente',
            name='nro_vivienda',
            field=models.IntegerField(default=0, verbose_name='Nro Vivienda'),
            preserve_default=False,
        ),
    ]
