# Generated by Django 3.2.4 on 2022-04-29 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220428_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastoscomune',
            old_name='residente',
            new_name='nro_vivienda',
        ),
    ]
