# Generated by Django 3.2.4 on 2022-04-29 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_residente_gastoscomune_nro_vivienda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastoscomune',
            old_name='nro_vivienda',
            new_name='residente',
        ),
    ]
