# Generated by Django 4.0.4 on 2022-05-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_cantreserva_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_reserva',
            new_name='fecha_pago',
        ),
        migrations.AlterField(
            model_name='cantreserva',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
