# Generated by Django 3.2.4 on 2022-04-29 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_nro_vivienda_gastoscomune_residente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastoscomune',
            old_name='residente',
            new_name='vivienda',
        ),
    ]
