# Generated by Django 4.0.4 on 2022-05-19 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_fecha_reserva_reserva_fecha_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoreserva',
            name='espacio',
        ),
        migrations.RemoveField(
            model_name='pagoreserva',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='pagoreserva',
            name='id_pago',
        ),
        migrations.AddField(
            model_name='pagoreserva',
            name='fecha_reserva',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pagoreserva',
            name='hora_reserva',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='pagoreserva',
            name='reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reserva'),
        ),
    ]
