# Generated by Django 3.2.4 on 2022-04-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_residente_gastoscomune_vivienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='nro_vivienda',
            field=models.CharField(max_length=5, verbose_name='Nro Vivienda'),
        ),
    ]
