# Generated by Django 4.0.4 on 2022-05-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_pagoreserva_espacio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='reservado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
