# Generated by Django 3.2.4 on 2022-04-29 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_residente_nro_vivienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoscomune',
            name='condominio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.condominio'),
            preserve_default=False,
        ),
    ]
