# Generated by Django 3.2.4 on 2022-04-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_gastoscomune_condominio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastoscomune',
            name='condominio',
        ),
    ]
