# Generated by Django 3.2.4 on 2022-04-29 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_gastoscomune_condominio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastoscomune',
            old_name='vivienda',
            new_name='nro_vivienda',
        ),
    ]
