# Generated by Django 3.2.4 on 2022-04-29 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_vivienda_gastoscomune_nro_vivienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastoscomune',
            name='nro_vivienda',
        ),
        migrations.AddField(
            model_name='gastoscomune',
            name='residente',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.residente'),
            preserve_default=False,
        ),
    ]
