# Generated by Django 3.2.4 on 2022-04-29 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220428_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoscomune',
            name='residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residente'),
        ),
    ]
