# Generated by Django 3.2.4 on 2022-04-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_gastoscomune_residente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GastosComune',
            new_name='GastosComunes',
        ),
        migrations.AlterModelOptions(
            name='gastoscomunes',
            options={'verbose_name_plural': 'Gastos Comunes'},
        ),
        migrations.AddField(
            model_name='reserva',
            name='imagen',
            field=models.ImageField(default=0, upload_to='img'),
            preserve_default=False,
        ),
    ]
