# Generated by Django 3.1.2 on 2022-05-27 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220526_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=500, verbose_name='Evento')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('conserje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conserje')),
            ],
            options={
                'verbose_name_plural': 'Evento Libro',
            },
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
