# Generated by Django 3.2.4 on 2022-04-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220429_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='imagen',
        ),
        migrations.AddField(
            model_name='espacio',
            name='imagen',
            field=models.ImageField(default=0, upload_to='img'),
            preserve_default=False,
        ),
    ]
