# Generated by Django 3.1.2 on 2022-04-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20220429_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='espacios'),
        ),
    ]
