# Generated by Django 3.1.2 on 2022-05-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20220429_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservasHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=9, verbose_name='Día')),
                ('incio', models.DateTimeField(verbose_name='Inicio')),
                ('termino', models.DateTimeField(verbose_name='Término')),
            ],
        ),
    ]
