# Generated by Django 3.1.2 on 2022-05-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_reservashorario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservashorario',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='reservashorario',
            name='incio',
            field=models.TimeField(verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='reservashorario',
            name='termino',
            field=models.TimeField(verbose_name='Término'),
        ),
    ]
