# Generated by Django 3.1.2 on 2022-05-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220501_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservashorario',
            old_name='incio',
            new_name='inicio',
        ),
    ]
